### ISSUE TITLE
Referencing issues / issue trackers

### ISSUE THREAD

**Issue by aaaaalbert** [secure-systems-lab/code-style-guidelines#12]
In @SeattleTestbed's code base, we sometimes put the relevant issue reference numbers in comments next to code that we think is not obvious or was changed in a non-obvious way. This augments adding issue references to commit messages, which is a [common way of closing issues too](https://help.github.com/articles/closing-issues-using-keywords/).

* Can we establish a better rule *when* to add issue references to comments in code?
* What format should the reference be? Do we want full URLs, or a plain `#123`, or `GithubOrg/repo#123`as proposed [here](SeattleTestbed/repy_v2#137) and mostly used in Seattle?

**Comment by baloyan** [comment]
In CacheCash we use plain #123, because most people (developers) trying to
find an issue code
even if it is a URL also less space and clear.

In general I think it should be flexible, but it should be clear for every
project.
For example, if we use plain #123 in CacheCash, we should always and
everywhere use plain
in CacheCash code.

**Comment by aaaaalbert** [comment]
Thanks! I agree that consistency is essential.

For context, in Seattle we sometimes have fixes in one repo that address documented issues in *other* repos. Thus our recemt use of the org--repo--issue format.

**Comment by lukpueh** [comment]
I'm really fine with all three suggestions, although the plain `#123` better only be used if the code is likely to remain associated with the GitHub repo. `GithubOrg/repo#123` and the full URL seem more stable. At any rate, I think this happens rarely enough, so that consistency (enforced by a guideline rule) doesn't seem a huge priority. Closing ...
